name: backend_rpl
description: "A new Flutter project for RPL backend."


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/